# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWeemZlOcd-uzb2zKdbDD0bY_tsDR82e
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('drive/MyDrive/ColabNotebooks/elec.csv', skipinitialspace=True)
df.info()

df

# Добавление меток месяцев
rows_in_df = 476
date_list = []
for i in range(1, rows_in_df + 1):
  date_list.append(i)
df['month'] = date_list
df

# График исходных данных

plt.scatter(df['month'],df['elec'], alpha=0.75)

plt.xlabel('month')
plt.ylabel('elec')
plt.show()

# Линия тренда
x = df['month']
y = df['elec']
plt.scatter(x, y)

z = np.polyfit(x, y, 1)
p = np.poly1d(z)
plt.plot(x,p(x),"r--")
plt.xlabel('month')
plt.ylabel('elec')

plt.show()

# Построение модели регрессии
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
y = df.iloc[:,:-1].values
X = df.iloc[:,1:].values

lr.fit(X, y)

# Пример сезонности за 1 год.
plt.scatter(X[1:36], y[1:36]);

plt.xlabel('month')
plt.ylabel('elec')
plt.show()

# Регрессия
y_lr = lr.predict(X)

plt.scatter(X, y);
plt.plot (X, y_lr, 'r');

plt.xlabel('month')
plt.ylabel('elec')
plt.show()

# Продление массива на 8 месяцев для создания предсказания
date_list = []
for i in range(477, 485):
  date_list.append(i)
z = np.concatenate((X, np.array(date_list).reshape(-1,1)), axis=0)

# Предсказание продаж
y_lr = lr.predict(z)

plt.scatter(X, y);
plt.plot (z, y_lr, 'r');

plt.xlabel('month')
plt.ylabel('elec')

plt.show()

#Продажи на прогназируемый период
print(y_lr[-8:])

